server:
  port: 8080

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /${segment}

        - id: wallet-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/api/v1/wallets/**
          filters:
            - RewritePath=/api/v1/wallets/(?<segment>.*), /${segment}

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - RewritePath=/api/v1/transactions/(?<segment>.*), /${segment}

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - RewritePath=/api/v1/notifications/(?<segment>.*), /${segment}

        - id: audit-service
          uri: lb://AUDIT-SERVICE
          predicates:
            - Path=/api/v1/audits/**
          filters:
            - RewritePath=/api/v1/audits/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://service-registry:8761/eureka/}

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: wallet-service
        url: /v3/api-docs/wallet-service
      - name: transaction-service
        url: /v3/api-docs/transaction-service
      - name: notification-service
        url: /v3/api-docs/notification-service
      - name: audit-service
        url: /v3/api-docs/audit-service
